"""empty message

Revision ID: 0af6eea448b1
Revises: a2b93c2896cc
Create Date: 2021-10-15 21:04:56.445434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0af6eea448b1'
down_revision = 'a2b93c2896cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dailymealplans_date', table_name='dailymealplans')
    op.create_index(op.f('ix_dailymealplans_date'), 'dailymealplans', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dailymealplans_date'), table_name='dailymealplans')
    op.create_index('ix_dailymealplans_date', 'dailymealplans', ['date'], unique=False)
    # ### end Alembic commands ###
